<?php
/*
 * Defines classes that may be loaded upon its first use by ClassLoader::load(). They are not
 * automatically loaded unless they are actually used. See <code>UtilsInterceptor</code> for
 * automatic loading of utils.
 */
$autoloadClasses = array(
		'AuthAware'                 => '/actions/AuthAware.php',
		'MessageAware'              => '/actions/MessageAware.php',
		'ModelAware'                => '/actions/ModelAware.php',
		'ParametersAware'           => '/actions/ParametersAware.php',
		'UploadAware'               => '/actions/UploadAware.php',
		'ValidationAware'           => '/actions/ValidationAware.php',
		'DatabaseException'         => '/database/DatabaseException.php',
		'DatabaseFactory'           => '/database/DatabaseFactory.php',
		'ResultSet'                 => '/database/ResultSet.php',
		'ResultSetArray'            => '/database/ResultSetArray.php',
		'SqlException'              => '/database/SqlException.php',
		'AbstractInterceptor'       => '/interceptors/AbstractInterceptor.php',
		'AuthInterceptor'           => '/interceptors/AuthInterceptor.php',
		'ErrorInterceptor'          => '/interceptors/ErrorInterceptor.php',
		'Interceptor'               => '/interceptors/Interceptor.php',
		'MessageInterceptor'        => '/interceptors/MessageInterceptor.php',
		'ModelInterceptor'          => '/interceptors/ModelInterceptor.php',
		'ParametersInterceptor'     => '/interceptors/ParametersInterceptor.php',
		'SessionInterceptor'        => '/interceptors/SessionInterceptor.php',
		'UploadInterceptor'         => '/interceptors/UploadInterceptor.php',
		'UtilsInterceptor'          => '/interceptors/UtilsInterceptor.php',
		'ValidationInterceptor'     => '/interceptors/ValidationInterceptor.php',
		'TransactionInterceptor'    => '/interceptors/TransactionInterceptor.php',
		'DataProvided'              => '/models/DataProvided.php',
		'ModelProxy'                => '/models/ModelProxy.php',
		'Models'                    => '/models/Models.php',
		'Proxy'                     => '/models/Proxy.php',
		'Validateable'              => '/models/Validateable.php',
		'ValidateableModelProxy'    => '/models/ValidateableModelProxy.php',
		'FileResponse'              => '/response/FileResponse.php',
		'JsonResponse'              => '/response/JsonResponse.php',
		'NotFoundResponse'          => '/response/NotFoundResponse.php',
		'PermanentRedirectResponse' => '/response/PermanentRedirectResponse.php',
		'PhpResponse'               => '/response/PhpResponse.php',
		'RedirectResponse'          => '/response/RedirectResponse.php',
		'Response'                  => '/response/Response.php',
		'SeeOtherResponse'          => '/response/SeeOtherResponse.php',
		'SmartyResponse'            => '/response/SmartyResponse.php',
		'XmlResponse'               => '/response/XmlResponse.php',
		'XsltResponse'              => '/response/XsltResponse.php',
		'Utils'                     => '/utils/Utils.php',
		'Validator'                 => '/validation/Validator.php',
		'ValidationHelper'          => '/validation/ValidationHelper.php');
?>
